http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  WeatherData:
    host: localhost
    path: "/weather/*"
  TemperatureData:
    host: localhost
    path: "/temperature/*"  
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  Weather:
    url: "https://friendly-cod-jjj4v4wwwqwc5pwv-3000.app.github.dev"
  Temperature:
    url: "https://friendly-cod-jjj4v4wwwqwc5pwv-3000.app.github.dev"
  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  Weather:
    apiEndpoints:
      - WeatherData
    policies:
      - log:
        action:
          message: "${req.method} ${req.originalUrl}"
      - proxy:
        - action:
          serviceEndpoint: Weather
          changeOrigin: true
  Temperature:
    apiEndpoints:
      - TemperatureData
    policies:
      - log:
        action:
          message: "${req.method} ${req.originalUrl}"
      - proxy:
        - action:
          serviceEndpoint: Temperature
          changeOrigin: true